@startwbs
skinparam DefaultFontSize 18
skinparam DefaultFontName Arial
<style>
rootNode {
    BackgroundColor white
    LineThickness 3.0
    RoundCorner 5.0
    Shadowing 3
    FontSize 15
}

arrow {
    LineThickness 0.5
    :depth(0) {
        LineStyle 0
        LineColor #2222DD
    }
    :depth(1) {
        LineStyle 1
        LineColor #a7adf8
    }
}

wbsDiagram {

}


</style>
title hhh


@endwbs